const quotes = [
    "The purpose of our lives is to be happy.",
    "Life is what happens when you're busy making other plans.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Never let the fear of striking out keep you from playing the game.",
    "Money and success don’t change people; they merely amplify what is already there.",
    "Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking.",
    "Not how long, but how well you have lived is the main thing.",
    "The unexamined life is not worth living.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Life is about making an impact, not making an income.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "A man who dares to waste one hour of time has not discovered the value of life.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The way to get started is to quit talking and begin doing.",
    "The successful warrior is the average man, with laser-like focus.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It is better to fail in originality than to succeed in imitation.",
    "The road to success and the road to failure are almost exactly the same.",
    "I never dreamed about success. I worked for it.",
    "Whatever the mind of man can conceive and believe, it can achieve.",
    "Strive not to be a success, but rather to be of value.",
    "You miss 100% of the shots you don't take.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The most difficult thing is the decision to act, the rest is merely tenacity.",
    "The best thing to hold onto in life is each other.",
    "Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world.",
    "The only thing we never get enough of is love; and the only thing we never give enough of is love.",
    "Love is composed of a single soul inhabiting two bodies.",
    "To love and be loved is to feel the sun from both sides.",
    "Love is not only something you feel, it is something you do.",
    "Love isn't something you find. Love is something that finds you.",
    "Life without love is like a tree without blossoms or fruit.",
    "Love cures people - both the ones who give it and the ones who receive it.",
    "I love you the more in that I believe you had liked me for my own sake and for nothing else.",
    "The only true wisdom is in knowing you know nothing.",
    "The journey of a thousand miles begins with a single step.",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    "An investment in knowledge pays the best interest.",
    "The great aim of education is not knowledge but action.",
    "It does not matter how slowly you go so long as you do not stop.",
    "Education is the most powerful weapon which you can use to change the world.",
    "Simplicity is the ultimate sophistication.",
    "Imagination is more important than knowledge.",
    "Learning never exhausts the mind.",
    "Time is money.",
    "The bad news is time flies. The good news is you're the pilot.",
    "The key is in not spending time, but in investing it.",
    "Time flies over us, but leaves its shadow behind.",
    "Time and tide wait for no man.",
    "The two most powerful warriors are patience and time.",
    "Time is the most valuable thing a man can spend.",
    "They always say time changes things, but you actually have to change them yourself.",
    "The trouble is, you think you have time.",
    "You may delay, but time will not.",
    "I have no special talent. I am only passionately curious.",
    "Early to bed and early to rise makes a man healthy, wealthy, and wise.",
    "Whatever you are, be a good one.",
    "You laugh at me because I'm different I laugh at you because you're all the same.",
    "If you don't like something, change it.",
    "The only journey is the one within.",
    "No act of kindness, no matter how small, is ever wasted.",
    "It is far better to be alone, than to be in bad company.",
    "If you cannot do great things, do small things in a great way.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Today you are you! That is truer than true! There is no one alive who is you-er than you!",
    "Change your thoughts and you change your world.",
    "Blessed are the hearts that can bend; they shall never be broken.",
    "Do all things with love.",
    "But man is not made for defeat. A man can be destroyed but not defeated.",
    "When you reach the end of your rope, tie a knot in it and hang on.",
    "There is nothing permanent except change.",
    "You cannot shake hands with a clenched fist.",
    "Let us sacrifice our today so that our children can have a better tomorrow.",
    "It is better to be feared than loved, if you cannot be both.",
    "Judge everyone and everything for yourself.",
    "There is no charm equal to tenderness of heart.",
    "All that we see or seem is but a dream within a dream.",
    "Lord, make me an instrument of thy peace. Where there is hatred, let me sow love.",
    "The future starts today, not tomorrow.",
    "Tough times never last, but tough people do.",
    "Ask not what your country can do for you – ask what you can do for your country.",
    "The best way to predict the future is to create it.",
    "Peace begins with a smile.",
    "Never, never, never give up.",
    "If my mind can conceive it, if my heart can believe it, then I can achieve it.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "If I cannot do great things, I can do small things in a great way."
];

const quoteBtn = document.getElementById('quote-btn');
const quoteDisplay = document.getElementById('quote-display');

quoteBtn.addEventListener('click', () => {
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    quoteDisplay.textContent = randomQuote;
    quoteDisplay.classList.remove('hidden');
});